type BigNumber {
  type: String
  hex: String
}

type Transaction {
  hash: String
  type: Int
  blockHash: String
  blockNumber: Int
  transactionIndex: Int
  from: String
  gasPrice: BigNumber
  maxPriorityFeePerGas: BigNumber
  maxFeePerGas: BigNumber
  gasLimit: BigNumber
  to: String
  value: BigNumber
  nonce: Int
  data: String
  r: String
  s: String
  v: Int
  chainId: Int
}

type Block {
  hash: String
  parentHash: String
  number: Int
  timestamp: Int
  nonce: String
  difficulty: Int
  gasLimit: BigNumber
  gasUsed: BigNumber
  miner: String
  extraData: String
  transactions: [Transaction]
  baseFeePerGas: BigNumber
}
